spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원 여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 20MB # 한 개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 20MB # 한 개 요청의 최대 사이즈 (default: 10MB)

  profiles:
    include: jwt # jwt.yml 불러오기

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성
      ddl-auto: update
      # 계속 유지
      # ddl-auto : none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY_ID}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

openai-service:
  api-key: ${OPENAI_API_KEY}
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000  # ms ??
    connect-timeout: 3000  # ms ??
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

#ffmpeg:
#  path: /usr/bin/ffmpeg
#ffprobe:
#  path: /usr/bin/ffprobe

#ffmpeg:
#  path: C:/Users/고동엽/Downloads/ffmpeg-7.0.1-essentials_build/bin/ffmpeg.exe
#ffprobe:
#  path: C:/Users/고동엽/Downloads/ffmpeg-7.0.1-essentials_build/bin/ffprobe.exe