jwt:
  secret: ${SECURITY_JWT_TOKEN_SECRET_KEY}

  access:
    expiration: 10800 # 유효시간 3시간 (1시간(3600초) * 3)
    header: Authorization

  refresh:
    expiration: 604800 # 유효시간 7일 (7일(604800초))
#    header: Authorization-refresh