spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: jwt # jwt.yml 불러오기

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성
      ddl-auto: create
      # 계속 유지
      # ddl-auto : none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY_ID}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false